"""empty message

Revision ID: 121979c09f2c
Revises:
Create Date: 2025-03-16 08:51:52.384658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "121979c09f2c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet_token", sa.Column("id", sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallet_token", "id")
    # ### end Alembic commands ###
