"""empty message

Revision ID: 250b4deb5290
Revises: 6852f18c124e
Create Date: 2025-03-27 00:15:43.953406

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "250b4deb5290"
down_revision: Union[str, None] = "6852f18c124e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flipsidecrypto_config",
        sa.Column(
            "swaps_parsed_until_block_timestamp",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.drop_column("flipsidecrypto_config", "swaps_parsed_until_block_timestamp")
    op.create_index("idx_token_is_metadata_parsed", "token", ["is_metadata_parsed"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_token_is_metadata_parsed", table_name="token")
    op.add_column(
        "flipsidecrypto_config",
        sa.Column(
            "swaps_parsed_untill_inserted_timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("flipsidecrypto_config", "swaps_parsed_until_block_timestamp")
    # ### end Alembic commands ###
