"""empty message

Revision ID: 42d3ec310bd0
Revises: 7d601b1f552b
Create Date: 2025-03-11 23:59:42.925545

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42d3ec310bd0"
down_revision: Union[str, None] = "7d601b1f552b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_statistic",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("winrate_7d", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column("total_token_buy_amount_usd_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_token_sell_amount_usd_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_profit_usd_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_profit_multiplier_7d", sa.Float(), nullable=True),
        sa.Column("total_token_7d", sa.Integer(), nullable=True),
        sa.Column("total_token_buys_7d", sa.Integer(), nullable=True),
        sa.Column("total_token_sales_7d", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell_7d", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_7d", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy_7d", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell_7d", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount_7d", sa.Integer(), nullable=True),
        sa.Column("token_avg_buy_amount_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_median_buy_amount_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_first_buy_avg_price_usd_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_first_buy_median_price_usd_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_avg_profit_usd_7d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_buy_sell_duration_avg_7d", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median_7d", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp_7d", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num_7d", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num_7d", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num_7d", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num_7d", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num_7d", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent_7d", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent_7d", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent_7d", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent_7d", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent_7d", sa.Float(), nullable=True),
        sa.Column("winrate_30d", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column("total_token_buy_amount_usd_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_token_sell_amount_usd_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_profit_usd_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_profit_multiplier_30d", sa.Float(), nullable=True),
        sa.Column("total_token_30d", sa.Integer(), nullable=True),
        sa.Column("total_token_buys_30d", sa.Integer(), nullable=True),
        sa.Column("total_token_sales_30d", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell_30d", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_30d", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy_30d", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell_30d", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount_30d", sa.Integer(), nullable=True),
        sa.Column("token_avg_buy_amount_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_median_buy_amount_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_first_buy_avg_price_usd_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_first_buy_median_price_usd_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_avg_profit_usd_30d", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_buy_sell_duration_avg_30d", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median_30d", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp_30d", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num_30d", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num_30d", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num_30d", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num_30d", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num_30d", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent_30d", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent_30d", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent_30d", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent_30d", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent_30d", sa.Float(), nullable=True),
        sa.Column("winrate_all", sa.DECIMAL(precision=40, scale=5), nullable=True),
        sa.Column("total_token_buy_amount_usd_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_token_sell_amount_usd_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_profit_usd_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("total_profit_multiplier_all", sa.Float(), nullable=True),
        sa.Column("total_token_all", sa.Integer(), nullable=True),
        sa.Column("total_token_buys_all", sa.Integer(), nullable=True),
        sa.Column("total_token_sales_all", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_and_sell_all", sa.Integer(), nullable=True),
        sa.Column("token_with_buy_all", sa.Integer(), nullable=True),
        sa.Column("token_sell_without_buy_all", sa.Integer(), nullable=True),
        sa.Column("token_buy_without_sell_all", sa.Integer(), nullable=True),
        sa.Column("token_with_sell_amount_gt_buy_amount_all", sa.Integer(), nullable=True),
        sa.Column("token_avg_buy_amount_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_median_buy_amount_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_first_buy_avg_price_usd_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_first_buy_median_price_usd_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_avg_profit_usd_all", sa.DECIMAL(precision=50, scale=20), nullable=True),
        sa.Column("token_buy_sell_duration_avg_all", sa.BigInteger(), nullable=True),
        sa.Column("token_buy_sell_duration_median_all", sa.BigInteger(), nullable=True),
        sa.Column("first_transaction_timestamp_all", sa.BigInteger(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_num_all", sa.Integer(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_num_all", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_2x_num_all", sa.Integer(), nullable=True),
        sa.Column("pnl_2x_5x_num_all", sa.Integer(), nullable=True),
        sa.Column("pnl_gt_5x_num_all", sa.Integer(), nullable=True),
        sa.Column("pnl_lt_minus_dot5_percent_all", sa.Float(), nullable=True),
        sa.Column("pnl_minus_dot5_0x_percent_all", sa.Float(), nullable=True),
        sa.Column("pnl_lt_2x_percent_all", sa.Float(), nullable=True),
        sa.Column("pnl_2x_5x_percent_all", sa.Float(), nullable=True),
        sa.Column("pnl_gt_5x_percent_all", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wallet_id"),
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_avg_buy_amount_30d"),
        "wallet_statistic",
        ["token_avg_buy_amount_30d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_avg_buy_amount_7d"),
        "wallet_statistic",
        ["token_avg_buy_amount_7d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_avg_buy_amount_all"),
        "wallet_statistic",
        ["token_avg_buy_amount_all"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_avg_profit_usd_30d"),
        "wallet_statistic",
        ["token_avg_profit_usd_30d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_avg_profit_usd_7d"),
        "wallet_statistic",
        ["token_avg_profit_usd_7d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_avg_profit_usd_all"),
        "wallet_statistic",
        ["token_avg_profit_usd_all"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_buy_sell_duration_median_30d"),
        "wallet_statistic",
        ["token_buy_sell_duration_median_30d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_buy_sell_duration_median_7d"),
        "wallet_statistic",
        ["token_buy_sell_duration_median_7d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_buy_sell_duration_median_all"),
        "wallet_statistic",
        ["token_buy_sell_duration_median_all"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_first_buy_median_price_usd_30d"),
        "wallet_statistic",
        ["token_first_buy_median_price_usd_30d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_first_buy_median_price_usd_7d"),
        "wallet_statistic",
        ["token_first_buy_median_price_usd_7d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_token_first_buy_median_price_usd_all"),
        "wallet_statistic",
        ["token_first_buy_median_price_usd_all"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_total_profit_multiplier_30d"),
        "wallet_statistic",
        ["total_profit_multiplier_30d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_total_profit_multiplier_7d"),
        "wallet_statistic",
        ["total_profit_multiplier_7d"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_total_profit_multiplier_all"),
        "wallet_statistic",
        ["total_profit_multiplier_all"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_statistic_total_profit_usd_30d"), "wallet_statistic", ["total_profit_usd_30d"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_statistic_total_profit_usd_7d"), "wallet_statistic", ["total_profit_usd_7d"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_statistic_total_profit_usd_all"), "wallet_statistic", ["total_profit_usd_all"], unique=False
    )
    op.create_index(op.f("ix_wallet_statistic_total_token_30d"), "wallet_statistic", ["total_token_30d"], unique=False)
    op.create_index(op.f("ix_wallet_statistic_total_token_7d"), "wallet_statistic", ["total_token_7d"], unique=False)
    op.create_index(op.f("ix_wallet_statistic_total_token_all"), "wallet_statistic", ["total_token_all"], unique=False)
    op.create_index(op.f("ix_wallet_statistic_winrate_30d"), "wallet_statistic", ["winrate_30d"], unique=False)
    op.create_index(op.f("ix_wallet_statistic_winrate_7d"), "wallet_statistic", ["winrate_7d"], unique=False)
    op.create_index(op.f("ix_wallet_statistic_winrate_all"), "wallet_statistic", ["winrate_all"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_statistic_winrate_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_winrate_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_winrate_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_token_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_token_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_token_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_profit_usd_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_profit_usd_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_profit_usd_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_profit_multiplier_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_profit_multiplier_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_total_profit_multiplier_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_first_buy_median_price_usd_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_first_buy_median_price_usd_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_first_buy_median_price_usd_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_buy_sell_duration_median_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_buy_sell_duration_median_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_buy_sell_duration_median_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_avg_profit_usd_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_avg_profit_usd_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_avg_profit_usd_30d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_avg_buy_amount_all"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_avg_buy_amount_7d"), table_name="wallet_statistic")
    op.drop_index(op.f("ix_wallet_statistic_token_avg_buy_amount_30d"), table_name="wallet_statistic")
    op.drop_table("wallet_statistic")
    # ### end Alembic commands ###
