"""empty message

Revision ID: 7d601b1f552b
Revises: a455bba053d8
Create Date: 2025-03-11 23:39:23.286094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d601b1f552b'
down_revision: Union[str, None] = 'a455bba053d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('last_activity_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wallet', sa.Column('first_activity_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'first_activity_timestamp')
    op.drop_column('wallet', 'last_activity_timestamp')
    # ### end Alembic commands ###
