"""empty message

Revision ID: 87910acfcef2
Revises: f2ef1b94f3a8
Create Date: 2025-03-11 06:39:59.333940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "87910acfcef2"
down_revision: Union[str, None] = "f2ef1b94f3a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_activities_info",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("last_activity_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_activity_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallet.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallet_activities_info_wallet_id"), "wallet_activities_info", ["wallet_id"], unique=True)
    op.drop_index("idx_wallet_last_activity", table_name="wallet")
    op.drop_column("wallet", "last_activity_timestamp")
    op.drop_column("wallet", "first_activity_timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wallet",
        sa.Column("first_activity_timestamp", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.add_column(
        "wallet",
        sa.Column("last_activity_timestamp", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.create_index("idx_wallet_last_activity", "wallet", ["last_activity_timestamp"], unique=False)
    op.drop_index(op.f("ix_wallet_activities_info_wallet_id"), table_name="wallet_activities_info")
    op.drop_table("wallet_activities_info")
    # ### end Alembic commands ###
