"""empty message

Revision ID: a455bba053d8
Revises: 87910acfcef2
Create Date: 2025-03-11 06:41:02.856469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a455bba053d8'
down_revision: Union[str, None] = '87910acfcef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_wallet_last_activity', 'wallet_activities_info', ['last_activity_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wallet_last_activity', table_name='wallet_activities_info')
    # ### end Alembic commands ###
